CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250905184349_Baseline') THEN
    CREATE TABLE aliases (
        aliasid integer GENERATED BY DEFAULT AS IDENTITY,
        humanreadableid text,
        recordstatusid integer NOT NULL,
        alias text NOT NULL,
        createdby integer NOT NULL,
        createddate timestamp with time zone NOT NULL,
        createdip text NOT NULL,
        modifiedby integer,
        modifieddate timestamp with time zone,
        modifiedip text,
        deletedby integer,
        deleteddate timestamp with time zone,
        deletedip text,
        CONSTRAINT "PK_aliases" PRIMARY KEY (aliasid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250905184349_Baseline') THEN
    CREATE TABLE contacttypes (
        contacttypeid integer GENERATED BY DEFAULT AS IDENTITY,
        contacttypename text,
        appliestoemail boolean NOT NULL,
        appliestophone boolean NOT NULL,
        appliestopostaladdress boolean NOT NULL,
        recordstatusid integer NOT NULL,
        CONSTRAINT "PK_contacttypes" PRIMARY KEY (contacttypeid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250905184349_Baseline') THEN
    CREATE TABLE coreidentity (
        coreidentityid integer GENERATED BY DEFAULT AS IDENTITY,
        preferredname text,
        firstname text,
        middlename text,
        lastname text,
        ssn bytea,
        dob timestamp with time zone,
        prefixid integer,
        suffixid integer,
        sexid integer,
        placeofbirthid integer,
        recordstatusid integer NOT NULL,
        createdby integer NOT NULL,
        createdip text NOT NULL,
        modifiedby integer NOT NULL,
        modifiedip text,
        CONSTRAINT "PK_coreidentity" PRIMARY KEY (coreidentityid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250905184349_Baseline') THEN
    CREATE TABLE coreidentityaliases (
        coreidentityaliasid integer GENERATED BY DEFAULT AS IDENTITY,
        humanreadableid text,
        recordstatusid integer NOT NULL,
        coreidentityid integer NOT NULL,
        aliasid integer NOT NULL,
        createdby integer NOT NULL,
        createddate timestamp with time zone NOT NULL,
        createdip text NOT NULL,
        modifiedby integer,
        modifieddate timestamp with time zone,
        modifiedip text,
        deletedby integer,
        deleteddate timestamp with time zone,
        deletedip text,
        CONSTRAINT "PK_coreidentityaliases" PRIMARY KEY (coreidentityaliasid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250905184349_Baseline') THEN
    CREATE TABLE coreidentityemails (
        coreidentityemailid integer GENERATED BY DEFAULT AS IDENTITY,
        coreidentityid integer NOT NULL,
        emailid integer NOT NULL,
        contacttypeid integer NOT NULL,
        contactsequence integer NOT NULL,
        recordstatusid integer NOT NULL,
        createdby integer NOT NULL,
        createddate timestamp with time zone NOT NULL,
        createdip text NOT NULL,
        modifiedby integer,
        modifieddate timestamp with time zone,
        modifiedip text,
        deletedby integer,
        deleteddate timestamp with time zone,
        deletedip text,
        CONSTRAINT "PK_coreidentityemails" PRIMARY KEY (coreidentityemailid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250905184349_Baseline') THEN
    CREATE TABLE coreidentityphones (
        coreidentityphoneid integer GENERATED BY DEFAULT AS IDENTITY,
        coreidentityid integer NOT NULL,
        phoneid integer NOT NULL,
        contacttypeid integer NOT NULL,
        contactsequence integer NOT NULL,
        recordstatusid integer NOT NULL,
        createdby integer NOT NULL,
        createddate timestamp with time zone NOT NULL,
        createdip text NOT NULL,
        modifiedby integer,
        modifieddate timestamp with time zone,
        modifiedip text,
        deletedby integer,
        deleteddate timestamp with time zone,
        deletedip text,
        CONSTRAINT "PK_coreidentityphones" PRIMARY KEY (coreidentityphoneid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250905184349_Baseline') THEN
    CREATE TABLE coreidentitypostaladdresses (
        coreidentitypostaladdressid integer GENERATED BY DEFAULT AS IDENTITY,
        coreidentityid integer NOT NULL,
        postaladdressid integer NOT NULL,
        contacttypeid integer NOT NULL,
        contactsequence integer NOT NULL,
        recordstatusid integer NOT NULL,
        createdby integer NOT NULL,
        createddate timestamp with time zone NOT NULL,
        createdip text NOT NULL,
        modifiedby integer,
        modifieddate timestamp with time zone,
        modifiedip text,
        deletedby integer,
        deleteddate timestamp with time zone,
        deletedip text,
        CONSTRAINT "PK_coreidentitypostaladdresses" PRIMARY KEY (coreidentitypostaladdressid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250905184349_Baseline') THEN
    CREATE TABLE defaultitems (
        defaultitemid integer GENERATED BY DEFAULT AS IDENTITY,
        defaultitempage text NOT NULL,
        defaultitemtab text,
        cancellink text,
        cancellinktext text,
        previouslink text,
        previouslinktext text,
        nextlink text,
        nextlinktext text,
        recordstatusid integer NOT NULL,
        CONSTRAINT "PK_defaultitems" PRIMARY KEY (defaultitemid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250905184349_Baseline') THEN
    CREATE TABLE emails (
        emailid integer GENERATED BY DEFAULT AS IDENTITY,
        emailaddress text,
        recordstatusid integer NOT NULL,
        createdby integer NOT NULL,
        createddate timestamp with time zone NOT NULL,
        createdip text NOT NULL,
        modifiedby integer,
        modifieddate timestamp with time zone,
        modifiedip text,
        deletedby integer,
        deleteddate timestamp with time zone,
        deletedip text,
        CONSTRAINT "PK_emails" PRIMARY KEY (emailid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250905184349_Baseline') THEN
    CREATE TABLE geography (
        geographyid integer GENERATED BY DEFAULT AS IDENTITY,
        geographyname text,
        geographytypeid integer NOT NULL,
        parentid integer,
        recordstatusid integer NOT NULL,
        CONSTRAINT "PK_geography" PRIMARY KEY (geographyid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250905184349_Baseline') THEN
    CREATE TABLE geographytypes (
        geographytypeid integer GENERATED BY DEFAULT AS IDENTITY,
        description text,
        recordstatusid integer NOT NULL,
        CONSTRAINT "PK_geographytypes" PRIMARY KEY (geographytypeid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250905184349_Baseline') THEN
    CREATE TABLE menuitems (
        menuitemid integer GENERATED BY DEFAULT AS IDENTITY,
        menuitemname text NOT NULL,
        menuitemtypeid integer NOT NULL,
        parentid integer,
        immediatelink text,
        nextlink text,
        cancellink text,
        previouslink text,
        sequenceid integer NOT NULL,
        recordstatusid integer NOT NULL,
        cancellinktext text,
        nextlinktext text,
        previouslinktext text,
        CONSTRAINT "PK_menuitems" PRIMARY KEY (menuitemid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250905184349_Baseline') THEN
    CREATE TABLE menuitemtypes (
        menuitemtypeid integer GENERATED BY DEFAULT AS IDENTITY,
        menuitemtypename text NOT NULL,
        recordstatusid integer NOT NULL,
        CONSTRAINT "PK_menuitemtypes" PRIMARY KEY (menuitemtypeid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250905184349_Baseline') THEN
    CREATE TABLE phones (
        phoneid integer GENERATED BY DEFAULT AS IDENTITY,
        phonenumber text,
        recordstatusid integer NOT NULL,
        createdby integer NOT NULL,
        createddate timestamp with time zone NOT NULL,
        createdip text NOT NULL,
        modifiedby integer,
        modifieddate timestamp with time zone,
        modifiedip text,
        deletedby integer,
        deleteddate timestamp with time zone,
        deletedip text,
        CONSTRAINT "PK_phones" PRIMARY KEY (phoneid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250905184349_Baseline') THEN
    CREATE TABLE postaladdresses (
        postaladdressid integer GENERATED BY DEFAULT AS IDENTITY,
        address1 text,
        address2 text,
        zipcode text,
        geographyid integer NOT NULL,
        recordstatusid integer NOT NULL,
        createdby integer NOT NULL,
        createddate timestamp with time zone NOT NULL,
        createdip text NOT NULL,
        modifiedby integer,
        modifieddate timestamp with time zone,
        modifiedip text,
        deletedby integer,
        deleteddate timestamp with time zone,
        deletedip text,
        CONSTRAINT "PK_postaladdresses" PRIMARY KEY (postaladdressid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250905184349_Baseline') THEN
    CREATE TABLE prefixsuffix (
        prefixsuffixid integer GENERATED BY DEFAULT AS IDENTITY,
        description text NOT NULL,
        category text NOT NULL,
        recordstatusid integer NOT NULL,
        CONSTRAINT "PK_prefixsuffix" PRIMARY KEY (prefixsuffixid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250905184349_Baseline') THEN
    CREATE TABLE sexes (
        sexid integer GENERATED BY DEFAULT AS IDENTITY,
        description text,
        recordstatusid integer NOT NULL,
        CONSTRAINT "PK_sexes" PRIMARY KEY (sexid)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250905184349_Baseline') THEN
    CREATE TABLE ssn_tokens (
        token uuid NOT NULL,
        encrypted_ssn bytea,
        created_at timestamp with time zone NOT NULL,
        expires_at timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ssn_tokens" PRIMARY KEY (token)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250905184349_Baseline') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250905184349_Baseline', '9.0.8');
    END IF;
END $EF$;
COMMIT;

