DROP TABLE IF EXISTS OrganizationsHistory CASCADE;
CREATE TABLE OrganizationsHistory (
	OrganizationsHistoryId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	RecordStatusId INT NOT NULL,
	OrganizationId INT NOT NULL,
	OrganizationName VARCHAR(255) NOT NULL,
	OrganizationTypeId INT NOT NULL,
	Address1 VARCHAR(255),
	Address2 VARCHAR(255),
	City VARCHAR(100),
	State VARCHAR(50),
	ZipCode VARCHAR(20),
	Phone VARCHAR(20),
	Email VARCHAR(255),
	Website VARCHAR(255),
	Operation VARCHAR(10) NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);

DROP TABLE IF EXISTS RecordStatuses CASCADE;
CREATE TABLE RecordStatuses (
	RecordStatusId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	StatusAbbreviation VARCHAR(50) NOT NULL UNIQUE,
	StatusName VARCHAR(255) NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);

DROP TABLE IF EXISTS CoreIdentityInvestigationRequests CASCADE;
CREATE TABLE CoreIdentityInvestigationRequests (
	CoreIdentityInvestigationRequestId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	RecordStatusId INT NOT NULL,
	InvestigationRequestId INT NOT NULL,
	CoreIdentityId INT NOT NULL,
	AssignmentDate TIMESTAMP NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);

DROP TABLE IF EXISTS ServiceProviders CASCADE;
CREATE TABLE ServiceProviders (
	ServiceProviderId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	RecordStatusId INT NOT NULL,
	ProviderName VARCHAR(100) NOT NULL UNIQUE,
	Description VARCHAR(255) NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);

DROP TABLE IF EXISTS InvestigationRequest CASCADE;
CREATE TABLE InvestigationRequest (
	InvestigationRequestId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	RecordStatusId INT NOT NULL,
	SpecialistAssignedId INT NULL,
	ServiceProviderId INT NULL,
	InvestigationTypeId INT NULL,
	SentDate TIMESTAMP NULL,
	CompletionDate TIMESTAMP NULL,
	ReceivedDate TIMESTAMP NULL,
	CoreIdentityId INT NOT NULL,
	AssignmentDate TIMESTAMP NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);

DROP TABLE IF EXISTS RelationshipTypeLookup CASCADE;

DROP TABLE IF EXISTS SocialMediaPlatformLookup CASCADE;

DROP TABLE IF EXISTS EmergencyContacts CASCADE;
CREATE TABLE EmergencyContacts (
	EmergencyContactId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	RecordStatusId INT NOT NULL,
	CoreIdentityId INT NOT NULL,
	PointOfContactId INT NOT NULL,
	RelationshipTypeId INT NOT NULL,
	ContactSequence INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);

DROP TABLE IF EXISTS Phones CASCADE;
CREATE TABLE Phones (
	PhoneId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	RecordStatusId INT NOT NULL,
	CountryCodeId INT NOT NULL,
	AreaCode VARCHAR(10) NULL,
	Number VARCHAR(20) NOT NULL,
	Extension VARCHAR(10) NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);

DROP TABLE IF EXISTS CoreIdentityPhones CASCADE;
CREATE TABLE CoreIdentityPhones (
	CoreIdentityPhoneId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	RecordStatusId INT NOT NULL,
	CoreIdentityId INT NOT NULL,
	PhoneId INT NOT NULL,
	ContactTypeId INT NOT NULL,
	ContactSequence INT NOT NULL DEFAULT 1,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);

DROP TABLE IF EXISTS Emails CASCADE;
CREATE TABLE Emails (
	EmailId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	RecordStatusId INT NOT NULL,
	EmailAddress VARCHAR(320) NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);

DROP TABLE IF EXISTS CoreIdentityEmails CASCADE;
CREATE TABLE CoreIdentityEmails (
	CoreIdentityEmailId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	RecordStatusId INT NOT NULL,
	CoreIdentityId INT NOT NULL,
	EmailId INT NOT NULL,
	ContactTypeId INT NOT NULL,
	ContactSequence INT NOT NULL DEFAULT 1,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);

DROP TABLE IF EXISTS PostalAddresses CASCADE;
CREATE TABLE PostalAddresses (
	PostalAddressId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	RecordStatusId INT NOT NULL,
	Address1 VARCHAR(255) NOT NULL,
	Address2 VARCHAR(255) NULL,
	City VARCHAR(100) NOT NULL,
	State VARCHAR(50) NOT NULL,
	ZipCode VARCHAR(20) NOT NULL,
	CountryId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);

DROP TABLE IF EXISTS CoreIdentityPostalAddresses CASCADE;
CREATE TABLE CoreIdentityPostalAddresses (
	CoreIdentityPostalAddressId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	RecordStatusId INT NOT NULL,
	CoreIdentityId INT NOT NULL,
	PostalAddressId INT NOT NULL,
	ContactTypeId INT NOT NULL,
	ContactSequence INT NOT NULL DEFAULT 1,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);

DROP TABLE IF EXISTS SocialMedia CASCADE;
CREATE TABLE SocialMedia (
	SocialMediaId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	RecordStatusId INT NOT NULL,
	Platform VARCHAR(50) NOT NULL,
	Handle VARCHAR(100) NOT NULL,
	Url VARCHAR(255) NULL,
	IsPrimary BOOLEAN NOT NULL DEFAULT FALSE,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);

DROP TABLE IF EXISTS CoreIdentitySocialMedia CASCADE;
CREATE TABLE CoreIdentitySocialMedia (
	CoreIdentitySocialMediaId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	RecordStatusId INT NOT NULL,
	CoreIdentityId INT NOT NULL,
	SocialMediaId INT NOT NULL,
	ContactTypeId INT NOT NULL,
	ContactSequence INT NOT NULL DEFAULT 1,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);

DROP TABLE IF EXISTS PointsOfContactPhones CASCADE;
CREATE TABLE PointsOfContactPhones (
	PointsOfContactPhoneId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	RecordStatusId INT NOT NULL,
	PointOfContactId INT NOT NULL,
	PhoneId INT NOT NULL,
	ContactTypeId INT NOT NULL,
	ContactSequence INT NOT NULL DEFAULT 1,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);

DROP TABLE IF EXISTS PointsOfContactEmails CASCADE;
CREATE TABLE PointsOfContactEmails (
	PointsOfContactEmailId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	RecordStatusId INT NOT NULL,
	PointOfContactId INT NOT NULL,
	EmailId INT NOT NULL,
	ContactTypeId INT NOT NULL,
	ContactSequence INT NOT NULL DEFAULT 1,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);


DROP TABLE IF EXISTS ContactTypeLookup CASCADE;

DROP TABLE IF EXISTS Contracts CASCADE;
CREATE TABLE Contracts (
	ContractId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	RecordStatusId INT NOT NULL,
	ContractNumber VARCHAR(100) NOT NULL UNIQUE,
	ContractName VARCHAR(255) NOT NULL,
	ContractTypeId INT NOT NULL,
	OrganizationId INT NOT NULL,
	VendorId INT,
	StartDate DATE NOT NULL,
	EndDate DATE,
	ContractValue DECIMAL(15, 2),
	Description TEXT,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);

DROP TABLE IF EXISTS Organizations CASCADE;
CREATE TABLE Organizations (
	OrganizationId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	RecordStatusId INT NOT NULL,
	OrganizationName VARCHAR(255) NOT NULL,
	OrganizationTypeId INT NOT NULL,
	Address1 VARCHAR(255),
	Address2 VARCHAR(255),
	City VARCHAR(100),
	State VARCHAR(50),
	ZipCode VARCHAR(20),
	Phone VARCHAR(20),
	Email VARCHAR(255),
	Website VARCHAR(255),
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);

DROP TABLE IF EXISTS Assignments CASCADE;
CREATE TABLE Assignments (
	AssignmentId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	RecordStatusId INT NOT NULL,
	WorkerId INT NOT NULL,
	OrganizationId INT NOT NULL,
	ContractId INT,
	AssignmentTypeId INT NOT NULL,
	AssignmentStatusId INT NOT NULL,
	StartDate DATE NOT NULL,
	EndDate DATE,
	HoursPerWeek DECIMAL(5, 2),
	HourlyRate DECIMAL(10, 2),
	Description TEXT,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);

DROP TABLE IF EXISTS TablePrefixes CASCADE;
CREATE TABLE TablePrefixes (
	PrefixId SERIAL PRIMARY KEY,
	HumanReadableId VARCHAR(20) NULL,
	TableName VARCHAR(50) NOT NULL UNIQUE,
	TablePrefix VARCHAR(255) NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIpAddress VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIpAddress VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIpAddress VARCHAR(45) NULL
);
DROP TABLE IF EXISTS Sexes CASCADE;
CREATE TABLE Sexes (
	SexId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableId VARCHAR(20) NULL,
	Description TEXT,
	RecordStatusId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
);

CREATE TABLE Geography (
	GeographyId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableId VARCHAR(20) NULL,
	Description TEXT,
	GeographyTypeId INT NOT NULL,
	RecordStatusId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
);

CREATE TABLE GeographyTypes (
	GeographyTypeId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableId VARCHAR(20) NULL,
	Description TEXT,
	RecordStatusId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
);
DROP TABLE IF EXISTS OrganizationTypes CASCADE;
CREATE TABLE OrganizationTypes (
	OrganizationTypeId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableId VARCHAR(20) NULL,
	Description TEXT,
	RecordStatusId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
);
DROP TABLE IF EXISTS PrefixSuffix CASCADE;
CREATE TABLE PrefixSuffix (
	PrefixSuffixId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableId VARCHAR(20) NULL,
	Description VARCHAR(255) NOT NULL,
	Category CHAR(6) NOT NULL,
	RecordStatusId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
);
DROP TABLE IF EXISTS CoreIdentity CASCADE;
CREATE TABLE CoreIdentity (
	CoreIdentityId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableId VARCHAR(20) NULL,
	PrefixId INT NULL,
	FirstName VARCHAR(50) NOT NULL,
	MiddleName VARCHAR(50) NULL,
	LastName VARCHAR(50) NOT NULL,
	SuffixId INT NULL,
	SSN CHAR(9) NOT NULL,
	DOB TIMESTAMP NOT NULL,
	PlaceOfBirthId INT NOT NULL,
	SexId INT NOT NULL,
	LegacyID VARCHAR(11) NULL,
	PreferredName VARCHAR(50) NULL,
	RecordStatusId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
	-- All FKs deferred
);
DROP TABLE IF EXISTS PointsOfContact CASCADE;
CREATE TABLE PointsOfContact (
	PointOfContactId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableId VARCHAR(20) NULL,
	PrefixId INT NULL,
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	SuffixId INT NULL,
	RecordStatusId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
	-- All FKs deferred
);
DROP TABLE IF EXISTS Vendors CASCADE;
CREATE TABLE Vendors (
	VendorId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableId VARCHAR(20) NULL,
	VendorName VARCHAR(255) NOT NULL,
	ContactPersonName VARCHAR(255) NULL,
	Address1 VARCHAR(255) NULL,
	Address2 VARCHAR(255) NULL,
	City VARCHAR(100) NULL,
	State VARCHAR(50) NULL,
	ZipCode VARCHAR(20) NULL,
	Phone VARCHAR(20) NULL,
	Email VARCHAR(255) NULL,
	Website VARCHAR(255) NULL,
	TaxId VARCHAR(50) NULL,
	RecordStatusId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
	-- All FKs deferred
);
DROP TABLE IF EXISTS ContactTypes CASCADE;
CREATE TABLE ContactTypes (
	ContactTypeId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableId VARCHAR(20) NULL,
	ContactTypeName VARCHAR(100) NOT NULL UNIQUE,
	Description TEXT NULL,
	RecordStatusId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
	-- All FKs deferred
);

DROP TABLE IF EXISTS ContractTypes CASCADE;
CREATE TABLE ContractTypes (
	ContractTypeId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableId VARCHAR(20) NULL,
	ContractTypeName VARCHAR(100) NOT NULL UNIQUE,
	Description TEXT NULL,
	RecordStatusId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
	-- All FKs deferred
);

DROP TABLE IF EXISTS CountryCodes CASCADE;
CREATE TABLE CountryCodes (
	CountryCodeId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableId VARCHAR(20) NULL,
	CountryCode VARCHAR(10) NOT NULL UNIQUE,
	CountryId INT NOT NULL,
	RecordStatusId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
	-- All FKs deferred
);

DROP TABLE IF EXISTS CountryLookup CASCADE;

DROP TABLE IF EXISTS DecisionLookup CASCADE;
DROP TABLE IF EXISTS Adjudications CASCADE;
CREATE TABLE Adjudications (
	AdjudicationID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableID VARCHAR(20) NULL,
	RecordStatusID INT NOT NULL,
	FirstAdjudicatorID INT NULL,
	FirstDecisionDate TIMESTAMP NULL,
	FirstDecisionID INT NULL,
	SecondAdjudicatorID INT NULL,
	SecondDecisionDate TIMESTAMP NULL,
	SecondDecisionID INT NULL,
	ThirdAdjudicatorID INT NULL,
	ThirdDecisionDate TIMESTAMP NULL,
	ThirdDecisionID INT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
);

DROP TABLE IF EXISTS Aliases CASCADE;
CREATE TABLE Aliases (
	AliasID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableID VARCHAR(20) NULL,
	RecordStatusID INT NOT NULL,
	CoreIdentityID INT NOT NULL,
	Alias VARCHAR(2000) NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
);

DROP TABLE IF EXISTS AssignmentTypes CASCADE;
CREATE TABLE AssignmentTypes (
	AssignmentTypeID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableID VARCHAR(20) NULL,
	RecordStatusID INT NOT NULL,
	AssignmentTypeName VARCHAR(100) NOT NULL UNIQUE,
	Description TEXT,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
);

DROP TABLE IF EXISTS AssignmentStatuses CASCADE;
CREATE TABLE AssignmentStatuses (
	AssignmentStatusID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableID VARCHAR(20) NULL,
	RecordStatusID INT NOT NULL,
	AssignmentStatusName VARCHAR(50) NOT NULL UNIQUE,
	Description TEXT,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
);
DROP TABLE IF EXISTS Packages CASCADE;
CREATE TABLE Packages (
	PackagesId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableId VARCHAR(20) NULL,
	SpecialistId INT NOT NULL,
	PackageTypeId INT NOT NULL,
	PackageComments TEXT NULL,
	SF86Required BOOLEAN NOT NULL,
	RecordStatusId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
	-- All FKs deferred
);

DROP TABLE IF EXISTS PackageTypes CASCADE;
CREATE TABLE PackageTypes (
	PackageTypesId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableId VARCHAR(20) NULL,
	PackageTypeName VARCHAR(100) NOT NULL UNIQUE,
	Description VARCHAR(255) NULL,
	RecordStatusId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
	-- All FKs deferred
);

DROP TABLE IF EXISTS FormTypes CASCADE;
CREATE TABLE FormTypes (
	FormTypesId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableId VARCHAR(20) NULL,
	FormTypeName VARCHAR(100) NOT NULL UNIQUE,
	Description VARCHAR(255) NULL,
	RecordStatusId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
	-- All FKs deferred
);

DROP TABLE IF EXISTS PackageFormEvents CASCADE;
CREATE TABLE PackageFormEvents (
	PackageFormEventsId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableId VARCHAR(20) NULL,
	PackageId INT NOT NULL,
	FormTypeId INT NOT NULL,
	EventType VARCHAR(20) NOT NULL,
	EventDate TIMESTAMP NOT NULL,
	Comments VARCHAR(255) NULL,
	RecordStatusId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
	-- All FKs deferred
);

DROP TABLE IF EXISTS AuditLogs CASCADE;
CREATE TABLE AuditLogs (
	AuditLogID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableID VARCHAR(20) NULL,
	TableName VARCHAR(100) NOT NULL,
	RecordID VARCHAR(100) NOT NULL,
	Operation VARCHAR(10) NOT NULL,
	ChangedData JSONB NULL,
	RecordStatusID INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
);
-- DDL-tables-new.sql
-- This file contains tables that appear only once in the original DDL or are easily deconflicted (same columns/types, possibly different order).
-- All table names are pluralized per DatabaseRules.md. All base columns and trigger requirements are applied.


-- Websites and junction tables
DROP TABLE IF EXISTS Websites CASCADE;
CREATE TABLE Websites (
	WebsiteId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableId VARCHAR(20) NULL,
	WebsiteUrl VARCHAR(255) NOT NULL,
	RecordStatusId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
);

DROP TABLE IF EXISTS OrganizationWebsites CASCADE;
CREATE TABLE OrganizationWebsites (
	OrganizationWebsiteId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	OrganizationId INT NOT NULL,
	WebsiteId INT NOT NULL,
	RecordStatusId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
);

DROP TABLE IF EXISTS VendorWebsites CASCADE;
CREATE TABLE VendorWebsites (
	VendorWebsiteId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	VendorId INT NOT NULL,
	WebsiteId INT NOT NULL,
	RecordStatusId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
);

-- CallsAndOrders table
DROP TABLE IF EXISTS CallsAndOrders CASCADE;
CREATE TABLE CallsAndOrders (
	CallsAndOrdersId INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	HumanReadableId VARCHAR(20) NULL,
	ContractId INT NOT NULL,
	CallOrOrderNumber VARCHAR(50) NOT NULL,
	PoPStartDate TIMESTAMP NOT NULL,
	PoPEndDate TIMESTAMP NOT NULL,
	COR INT NOT NULL, -- FK to CoreIdentity
	ACOR INT NULL,    -- FK to CoreIdentity
	CO INT NULL,      -- FK to CoreIdentity
	CS INT NULL,      -- FK to CoreIdentity
	RecordStatusId INT NOT NULL,
	CreatedBy INT NOT NULL,
	CreatedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CreatedIP VARCHAR(45) NOT NULL DEFAULT '::0',
	ModifiedBy INT NULL,
	ModifiedDate TIMESTAMP NULL,
	ModifiedIP VARCHAR(45) NULL,
	DeletedBy INT NULL,
	DeletedDate TIMESTAMP NULL,
	DeletedIP VARCHAR(45) NULL
	-- All FKs deferred
);
